# -*- coding: utf-8 -*-
"""IndicTrans_using_google_translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tATCzB07hjHUIKTQ9lzCekg-yz82zTFY
"""


import streamlit as st
from googletrans import Translator

# Initialize the Google Translator
translator = Translator()

# Example list of English sentences
sentences = [
    "When I was young, I used to go to the park every day.",
    "He has many old books, which he inherited from his ancestors.",
    "I can't figure out how to solve my problem.",
    "She is very hardworking and intelligent, which is why she got all the good marks.",
    "We watched a new movie last week, which was very inspiring.",
    "If you had met me at that time, we would have gone out to eat.",
    "She went to the market with her sister to buy a new sari.",
    "Raj told me that he is going to his grandmother's house next month.",
    "All the kids were having fun at the party and were eating lots of sweets.",
    "My friend has invited me to his birthday party, and I will give him a gift.",
]

# Translate each sentence to Hindi and Tamil
translations_hindi = [translator.translate(sentence, src='en', dest='hi').text for sentence in sentences]
translations_tamil = [translator.translate(sentence, src='en', dest='ta').text for sentence in sentences]

# Create a dropdown for language selection
language = st.selectbox('Select Language:', ['Select Language', 'English', 'Hindi', 'Tamil'])

# Display sentences based on the selected language
if language == 'English':
    st.subheader("English Sentences")
    for sentence in sentences:
        st.write(sentence)

elif language == 'Hindi':
    st.subheader("Hindi Translations")
    for translation in translations_hindi:
        st.write(translation)

elif language == 'Tamil':
    st.subheader("Tamil Translations")
    for translation in translations_tamil:
        st.write(translation)
